$UVMF_VIP_LIBRARY_HOME/interface_packages/decode_in_pkg/decode_in_pkg_hdl.sv

$UVMF_VIP_LIBRARY_HOME/interface_packages/decode_in_pkg/src/decode_in_if.sv
$UVMF_VIP_LIBRARY_HOME/interface_packages/decode_in_pkg/src/decode_in_monitor_bfm.sv
$UVMF_VIP_LIBRARY_HOME/interface_packages/decode_in_pkg/src/decode_in_driver_bfm.sv